FROM mcr.microsoft.com/devcontainers/base:bookworm

RUN \
    apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get -y install --no-install-recommends \
    bash \
    zsh \
    git \
    python3 \
    python3-venv \
    ;
